### ISSUE TITLE
Refine Architecture/Workflow for IA for 128

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/application-form#108]
As per conversation - uploading of Word template, linking to applicant account, versioning

Save to Google Drive? 
Virus scanning (done by drive?)

Reporting on missing assessments-reminder emails (already remarked in existing tickets).

**Comment by ollietreend** [comment]
Proposed directory structure for Google Drive:

One Team Drive for all IA submissions

Directory structure:

```
VACANCY_ID/
└──  APPLICANT_ID/
    ├── ASSESSOR_1_EMAIL.docx
    └── ASSESSOR_2_EMAIL.docx
```
