### ISSUE TITLE
Write application record when user begins application

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/application-form#28]
Requires https://github.com/JudicialAppointmentsCommission/digital-platform/issues/93
Requires https://github.com/JudicialAppointmentsCommission/digital-platform/issues/94
Requires https://github.com/JudicialAppointmentsCommission/digital-platform/issues/97

We don't know which of the dependencies we'll do first, but this ticket only requires one.  Delete the other two once the first one is completed. 

## Background 

We are now at the point where we require the application state–this is how the confirmation email will be triggered for this phase.   

The code is in place in the front end app, but is not yet enabled.  

## Done when

- [ ] A new record gets written in the `applications` collection when a user begins the exercise specific questions.
- [ ] The application contains a link to the user's record in the `applicants` collection.
- [ ] The application record contains a link to vacancy the user is applying for. 
- [ ] The application has the status of `draft`.

**Comment by sme-JAC** [comment]
Superseded by 93,94 or 97.  Not sure which
