### ISSUE TITLE
National Insurance Number wording

### ISSUE THREAD

**Issue by ollietreend** [JudicialAppointmentsCommission/application-form#45]
Change 'National Insurance Number' wording on Personal Details page to be:

"It's on your National Insurance card, payslip or P60
For example QQ 12 34 56 C"

Note: no quotes around example, and remove reference to benefit letter.

**Comment by CbarkerJAC** [comment]
Following the policy team's review of the online app platform: As per GDS guidance can you please restrict the length to 13 characters. Currently you can enter as many characters as you like.

**Comment by ollietreend** [comment]
Having just spoken with @CbarkerJAC, we've agreed that we won't implement a character limit on this field. The GDS guidance states that the form must allow for (at least) 13 characters, rather than imposing a limit of 9 – and the input field, as it currently stands, does allow for this.
