### ISSUE TITLE
Change wording on Qualifications page

### ISSUE THREAD

**Issue by tatyree** [JudicialAppointmentsCommission/application-form#52]
Depend on  https://github.com/JudicialAppointmentsCommission/digital-platform/issues/76

On 'Your Qualifications' page, could you change the question 'When were you admitted as a solictor?' to 'When were you entered on the Roll?'.

Could you then remove the question 'Are you currently on the Roll?'. You do not have to currently be on the Roll to be eligible.

**Comment by JonSJAC** [comment]
Please change page title by removing the word Your, so it should be Qualifications

Please change the question What are you qualified as, to read Are you qualified as a:
Barrister
Solicitor 
Allow candidate to choose both options

Please change the question where did you qualify?, to Did you qualify in England and Wales?
Yes
No
If No, bring up a prompt to contact the JAC, along the same wording as Citizenship prompt.

Under Qualification date, the year starts at 0, please can it start at 1960.

Under When were you called to the Bar, the year starts at 0, please can it start at 1960.

For Solicitor, When were you entered onto the roll (currently reads when were you admitted as a solicitor, see Todds comment above), please can the year start at 1960, as it currently starts at 0.
