### ISSUE TITLE
Content for validation message on page

### ISSUE THREAD

**Issue by ollietreend** [JudicialAppointmentsCommission/application-form#64]
When a user logs in who hasn't yet verified their email address, we'll show this message. They can't continue to start their application until they've completed this step.

Relevant guidance from GDS: [Designing the ‘activate your account’ page](https://design-system.service.gov.uk/patterns/confirm-an-email-address/#designing-the-activate-your-account-page)

---

### Verify your email address

We need to make sure we've got the right email address for you.

We've sent an email to **user@example.com** containing a link to verify your email address.

Click the link in the email to complete your registration and start your application.

▼ **Help! I haven't received the email yet**

> It could take up to 10 minutes for our email to arrive.
>
> Don't forget to check your 'spam' or 'junk mail' folder in case it didn't go into your inbox.
>
> If it still hasn't arrived after 10 minutes, you can resend the email:
>
> [ Resend email ]

**Comment by ollietreend** [comment]
I've followed the [GDS guidance](https://design-system.service.gov.uk/patterns/confirm-an-email-address/#designing-the-activate-your-account-page) when considering what to put on this page.

@NoraJAC please tweak wording as you see fit and I'll pick up the changes in snagging.

**Comment by NoraJAC** [comment]
Verify your email address

The JAC needs to make sure we have the right email address for you.

We've sent an email to user@example.com containing a link to verify your email address.

Follow the link to complete your registration and start your application.

▼ Help! I haven't received the email yet

    It could take up to 10 minutes for the email to arrive.

    Don't forget to check your 'spam' or 'junk mail' folder in case it didn't go into your inbox.

    If it still hasn't arrived after 10 minutes, you can resend the email:

    [ Resend email ]
